[tool.poetry]
name = "quickmenu"
version = "0.1.0"
description = ""
authors = ["chin98edwin <edwin_chin98@hotmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
